<?php


namespace App\Domain\Customers\Resources;


class CustomersAgeCollectionResource extends CustomersCollectionResource
{
    protected function getResource($object)
    {
        $res = parent::getResource($object); // TODO: Change the autogenerated stub

        return array_merge($res, [
            'age' => $object->age,
        ]);
    }
}
